### ISSUE TITLE
"No stream deck device found" (Windows 10)

### ISSUE THREAD

**Issue by CrocodileCroco** [dh1tw/streamdeck#7]
When i'm using the lib i always have the following error, even if the stream deck is plugged in : 

2021/08/27 13:10:59 no stream deck device found
panic: no stream deck device found

goroutine 1 [running]:
log.Panic(0xc0001bdac8, 0x1, 0x1)
        C:/Program Files/Go/src/log/log.go:354 +0xb7
github.com/dh1tw/streamdeck-examples/cmd.icons(0x313d20, 0x819a70, 0x0, 0x0)
        C:/Users/schomz/go/src/github.com/dh1tw/streamdeck-examples/cmd/icons.go:32 +0xdc
github.com/spf13/cobra.(*Command).execute(0x313d20, 0x819a70, 0x0, 0x0, 0x313d20, 0x819a70)
        C:/Users/schomz/go/src/github.com/spf13/cobra/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x314720, 0xc00003e000, 0x200000003, 0xc00003e000)
        C:/Users/schomz/go/src/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/schomz/go/src/github.com/spf13/cobra/command.go:902
github.com/dh1tw/streamdeck-examples/cmd.Execute()
        C:/Users/schomz/go/src/github.com/dh1tw/streamdeck-examples/cmd/root.go:22 +0x38
main.main()
        C:/Users/schomz/go/src/github.com/dh1tw/streamdeck-examples/main.go:6 +0x27

**Comment by jcoconnor** [comment]
This looks to be the Product ID Definition which is set to 96 and needs to be changed to 109 I think.

Once I did that manually in my workspace I was able to enumerate the device ok.
